server:
  port: 0  # 랜덤 포트 사용 

spring:
  application:
    name: auth-service

service:
  jwt:
    expiration: 86400000 # 유효기간: 1일 (밀리초 단위).
    secret-key: "bXlfc3VwZXJfc2VjcmV0X2tleV9oZWVkYWU5M19tc2FfcHJvamVjdF8xMjM0"