server:
  port: 0  # 랜덤 포트 사용 

spring:
  application:
    name: auth-service

# JWT 토큰 생성에 필요한 설정값
token:
  expiration_time: 86400000 # 유효기간: 1일 (밀리초 단위)
  secret: my_super_secret_key_heedae93_msa_project_1234 # User Service와 똑같은 키여야 함!